os: linux
dist: focal

language: shell

addons:
  hosts:
    - le1.wtf
    - le2.wtf
    - le3.wtf

env:
  global:
    - IMAGE=pinidh/letsencrypt-nginx-proxy-companion
    - NGINX_CONTAINER_NAME=nginx-proxy
    - DOCKER_GEN_CONTAINER_NAME=nginx-proxy-gen
    - TEST_DOMAINS=le1.wtf,le2.wtf,le3.wtf
    - DOCKER_COMPOSE_VERSION=1.24.0

jobs:
  include:
    - env: SETUP=2containers
    - env: SETUP=3containers

before_install:
  - test/travis/update-docker-compose.sh

install:
  - docker build -t "$IMAGE" .
  - docker inspect "$IMAGE"
  - docker run --rm "$IMAGE" acme.sh --version
  - docker images

before_script:
  - git clone https://github.com/docker-library/official-images.git official-images
  - test/setup/setup-boulder.sh
  - test/setup/setup-nginx-proxy.sh
  - docker pull nginx:alpine

script:
  - official-images/test/run.sh "$IMAGE"
  - test/run.sh "$IMAGE"

after_failure:
  - test/travis/containers-logs.sh
